### PR TITLE
Toothpaste Crazy

### LINKED ISSUE #21: Add Calvy's Meme
closes #49

### PR DESCRIPTION
**Pull request by armstrca**
closes #21

### CODE REVIEW

**Review by brendareyes-techprep — APPROVED** [review]
im a little scared

**Review by thierrychau — DISMISSED** [review]
REPORT

**Review by thatcantbeso — APPROVED** [review]
9/10 dentists approve

**Review by carmanchiu — APPROVED** [review]
what a masterpaste

**Comment by carmanchiu** [comment]
> what a masterpaste

sorry bad pun

**Pull request merged**
