### PR TITLE
Add cat meme

### PR DESCRIPTION
**Pull request by heratyian**

### CODE REVIEW

**Comment by heratyian** [comment]
Can you review this @DPI-WE/teaching-assistants ?

**Review by jptran0 — APPROVED** [review]
😺

**Comment by heratyian** [comment]
> Can you review this @DPI-WE/teaching-assistants

cc: @Meenoow

**Review by Meenoow — APPROVED** [review]
👍

**Review by jptran0 — APPROVED** [review]
😺

**Review by Meenoow — APPROVED** [review]

**Pull request merged**
