### PR TITLE
116 jr add meme

### LINKED ISSUE #116: jr image not showing up

### PR DESCRIPTION
**Pull request by joannarodriguez134**
closed #116

### CODE REVIEW

**Review by Shafaq-Juda — APPROVED** [review]
Cool!

**Review by salcasta — CHANGES_REQUESTED** [review]
please delete reid from the old table

**Review by lsampson1974 — APPROVED** [review]
Looks good to me.

**Review by Shafaq-Juda — APPROVED** [review]
👍🏻

**Review by salcasta — APPROVED** [review]
Nice

**Pull request merged**
