### PR TITLE
Add Thinker meme

### LINKED ISSUE #8: Add thinker meme 🤔

### PR DESCRIPTION
**Pull request by Brian-Waddell**
closes #8

### CODE REVIEW

**Review by carmanchiu — APPROVED** [review]
me

**Review by JaredBears — CHANGES_REQUESTED** [review]
It looks like you deleted Mena's meme.  You may want to add that back in.

```md
| ![](./assets/css_pro.webp) | [Mena Castillo](https://github.com/Meenoow) | [source](https://medium.com/agileactors/program-memes-45f69695457e) |
```
Mena's meme is in the file I just pasted mine in between ian and mena

**Review by jacobhoffmann257 — APPROVED** [review]

**Review by akincampbell — APPROVED** [review]

**Review by ajgarner98 — APPROVED** [review]
Smart

**Review by thatcantbeso — APPROVED** [review]
hehe where the statue goin'

**Comment by JaredBears** [comment]
> It looks like you deleted Mena's meme. You may want to add that back in.
> 
> ```
> |  | [Mena Castillo](https://github.com/Meenoow) | [source](https://medium.com/agileactors/program-memes-45f69695457e) |
> ```
[edit]
Nevermind, it looks like its back in there now

**Review by JaredBears — APPROVED** [review]

**Comment by JaredBears** [comment]
> It looks like you deleted Mena's meme. You may want to add that back in.
> 
> ```
> |  | [Mena Castillo](https://github.com/Meenoow) | [source](https://medium.com/agileactors/program-memes-45f69695457e) |
> ```

Never mind it looks like its fixed now

**Pull request merged**
