### PR TITLE
Djvon has a meme

### LINKED ISSUE #239: Djvon meme
Add a cool new meme

### PR DESCRIPTION
**Pull request by dsimp**

### CODE REVIEW

**Review by bibimbop123 — APPROVED** [review]

**Review by dgarcia13-99 — CHANGES_REQUESTED** [review]
Make sure to link your issue to the pull request! (E.g. closes #(number of issue)).

**Comment by dsimp** [comment]
@dgarcia13-99 Ive linked the issue , thanks!

**Review by jessjno — APPROVED** [review]
nice!

**Review by dgarcia13-99 — APPROVED** [review]
looks good!

**Pull request merged**
