### PR TITLE
closes #24

### LINKED ISSUE #24: Add Alejandro's Meme

### PR DESCRIPTION
**Pull request by alejlopez139**

### CODE REVIEW

**Review by brendareyes-techprep — APPROVED** [review]
I approve this message.

**Review by carmanchiu — DISMISSED** [review]
theres a duplicate dood

**Review by thatcantbeso — DISMISSED** [review]
there are extra lines

**Comment by alejlopez139** [comment]
> there are extra lines

I think i fixed them

**Comment by alejlopez139** [comment]
> theres a duplicate dood

Nah, I don't see them

**Review by Jorge-Pioquinto — APPROVED** [review]

**Review by JaredBears — APPROVED** [review]

**Pull request merged**
