### PR TITLE
Adding alonzo rice meme

### LINKED ISSUE #247: Adding Alonzo's meme
adding pic,  submitted by, and source.

### PR DESCRIPTION
**Pull request by ricealonzo**
closes #247

### CODE REVIEW

**Comment by heratyian** [comment]
Good job @ricealonzo . Will want to add this meme to your section 2024-10-1-sdf. @teresa-c-pham has created a section on her pull request https://github.com/DPI-WE/request-to-meme/pull/244 Will need to merge this pr after hers

**Review by aldoportillo — DISMISSED** [review]
Wait for Theresa's PR to merge and add it under that section.

**Comment by ricealonzo** [comment]
Thank you Ian and Aldo. I have made the corrections.

**Review by teresa-c-pham — APPROVED** [review]
Hilarious!

**Review by bibimbop123 — APPROVED** [review]

**Review by ricealonzo — COMMENTED** [review]
ok

**Pull request merged**
