### PR TITLE
added stealing meme

### PR DESCRIPTION
**Pull request by EthanKH**

### CODE REVIEW

**Review by thatcantbeso — APPROVED** [review]
i like perry

**Review by thatcantbeso — DISMISSED** [review]
You added an extra Dmitrii

**Review by JaredBears — DISMISSED** [review]
Looks like Dmitrii's may have been duplicated on yours?

**Review by akincampbell — APPROVED** [review]
Great meme!

**Review by JaredBears — APPROVED** [review]

**Pull request merged**
